# Generated by Django 5.1.7 on 2025-04-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('estado_reserva', '0001_initial'),
        ('pistas', '0001_initial'),
        ('resultados', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado_reserva.estadoreserva')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pistas.pistas')),
                ('resultado_partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resultados.resultados')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
