# Generated by Django 5.2 on 2025-05-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipousuario',
            old_name='tipo',
            new_name='nombre',
        ),
    ]
