# Generated by Django 5.1.7 on 2025-04-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_1', models.IntegerField()),
                ('resultado_2', models.IntegerField()),
                ('jugador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_1', to='usuarios.usuarios')),
                ('jugador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugador_2', to='usuarios.usuarios')),
                ('jugador_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugador_3', to='usuarios.usuarios')),
                ('jugador_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugador_4', to='usuarios.usuarios')),
            ],
        ),
    ]
