# Generated by Django 5.2 on 2025-04-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_rename_resultados_resultado'),
        ('usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='jugador_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugador_1', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='jugador_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugador_2', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='jugador_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugador_3', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='jugador_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugador_4', to='usuarios.usuario'),
        ),
    ]
