# Generated by Django 5.1.7 on 2025-04-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_rename_clubs_club'),
        ('estado_pista', '0001_initial'),
        ('partidos', '0002_rename_partidos_partido'),
        ('pistas', '0001_initial'),
        ('tipo_pista', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pistas',
            new_name='Pista',
        ),
    ]
