# Generated by Django 5.1.7 on 2025-04-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_rename_clubs_club'),
        ('estado_reserva', '0001_initial'),
        ('invitaciones', '0001_initial'),
        ('partidos', '0001_initial'),
        ('pistas', '0001_initial'),
        ('resultados', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partidos',
            new_name='Partido',
        ),
    ]
