# Generated by Django 5.1.7 on 2025-04-03 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('estado_pista', '0001_initial'),
        ('tipo_pista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.clubs')),
                ('estado_pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estado_pista.estadopista')),
                ('tipo_pista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_pista.tipopista')),
            ],
        ),
    ]
